springdoc:
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:postgresql://db:5432/backend
    username: postgres
    password: postgres

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console.enabled: true # http://localhost:8080/h2-console
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true